### ISSUE TITLE
Docs: Getting Started 

### ISSUE THREAD

**Issue by peterbsmith2** [jamespatrickgibson/union#34]
Current:

\#\#\# Add Theme and Core CSS

```svelte
<link rel="stylesheet" href="https://unpkg.com/union-design-system/dist/theme.css"/>
<link rel="stylesheet" href="https://unpkg.com/union-design-system/dist/union.css"/>
```

---

I'm putting this into a sapper project, guessing that "template.html" is the way to do it. 

I could use guidance on the place to put these files.

**Comment by jamespatrickgibson** [comment]
This is a great point. I'll add this to the getting started docs, for Svelte specific installs

**Comment by jamespatrickgibson** [comment]
@peterbsmith2 Docs now updated to include svelte specific style includes.
